### ISSUE TITLE
default clientVersion used in helm mixin no matter of what clientVersion is specified in porter.yaml

### ISSUE THREAD

**Issue by a-r-o-n** [deislabs/porter-helm#65]
Hi, 

No matter what I specify in the porter.yaml for the helm mixin when I execute `porter build --debug` always the helm v2.15.2 gets downloaded into the invocation image.

porter.yaml:
```yaml
mixins:
- helm:
    clientVersion: v3.1.2
```

.cnab/bundle.json:
```json
"mixins":{"helm":{}}}} 
```
Dockerfile:
`RUN apt-get update && \
 apt-get install -y curl && \
 curl -o helm.tgz https://get.helm.sh/helm-v2.15.2-linux-amd64.tar.gz && \
`

porter version: porter v0.26.0-beta.1 (b15c4109)

**Comment by vdice** [comment]
Thank you for the issue.  It looks like we haven't cut a release of this mixin that includes the changes to [enable version specification](https://github.com/deislabs/porter-helm/pull/64).  I'll test the candidate and if all looks good, cut a release.

**Comment by vdice** [comment]
Note: there exists a helm3 mixin with support for clientVersion as well: https://github.com/mchorfa/porter-helm3.  (From the author of the PR in this repo).  You might try this in the meantime.

This mixin still has logic tied to the v2 version of Helm (pending https://github.com/deislabs/porter-helm/issues/50#issuecomment-606344338), so if v3 is desired, I'd recommend the aforementioned mixin for now.

**Comment by a-r-o-n** [comment]
Thank you for the mixin suggestion. It worked!

**Comment by vdice** [comment]
Closing now that we've cut a [release](https://github.com/deislabs/porter-helm/releases/tag/v0.12.0-beta.1) that includes this functionality.
